# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod vendor
builds:
- main: ./cli/.
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 7
archives:
  - id: s3sync
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}MacOS_
      {{- else if eq .Os "linux" }}Linux_
      {{- else if eq .Os "windows" }}Windows_
      {{- else if eq .Os "freebsd" }}FreeBSD_
      {{- else if eq .Os "netbsd" }}NetBSD_
      {{- else if eq .Os "openbsd" }}OpenBSD_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
